version: "3"
services:
  app:
    build: ./docker/app
    volumes:
      - ../:/workspace:cached
    ports:
      - 80:80
    init: true
    depends_on:
      - db
    environment:
      APP_ENV: local
      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSION_PGSQL: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      APACHE_DOCUMENT_ROOT: /workspace/public
  mysql:
    image: mysql:5.7
    hostname: db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: careers_app
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
